/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Macklon
 */
public class Seat extends javax.swing.JFrame {
    
    ArrayList list = new ArrayList(); 
    
    /**
     * Creates new form seat
     */
    public Seat() {
        initComponents(); 
        
        lsbname.setText(Login.bname);
        array();
        check();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lsbname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbseats = new javax.swing.JLabel();
        lbprice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c11 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c20 = new javax.swing.JCheckBox();
        c19 = new javax.swing.JCheckBox();
        c17 = new javax.swing.JCheckBox();
        c16 = new javax.swing.JCheckBox();
        c18 = new javax.swing.JCheckBox();
        c15 = new javax.swing.JCheckBox();

        jLabel1.setText("₹");

        jLabel4.setText("jLabel4");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(194, 62, 75));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select your seat");

        lsbname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lsbname.setForeground(new java.awt.Color(255, 255, 255));
        lsbname.setText("bname");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/back.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lsbname)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lsbname)))
                .addGap(25, 25, 25))
        );

        lbseats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbseats.setText("Seats :");

        lbprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbprice.setText("0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbseats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbprice)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbseats)
                    .addComponent(lbprice))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(194, 62, 75));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DONE");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        c1.setText("1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setText("2");
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });

        c4.setText("4");
        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c4MouseClicked(evt);
            }
        });

        c3.setText("3");
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
        });

        c5.setText("5");
        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c5MouseClicked(evt);
            }
        });

        c6.setText("6");
        c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c6MouseClicked(evt);
            }
        });

        c10.setText("10");
        c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c10MouseClicked(evt);
            }
        });
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });

        c12.setText("12");
        c12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c12MouseClicked(evt);
            }
        });

        c14.setText("14");
        c14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c14MouseClicked(evt);
            }
        });

        c7.setText("7");
        c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c7MouseClicked(evt);
            }
        });

        c13.setText("13");
        c13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c13MouseClicked(evt);
            }
        });

        c8.setText("8");
        c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c8MouseClicked(evt);
            }
        });

        c11.setText("11");
        c11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c11MouseClicked(evt);
            }
        });

        c9.setText("9");
        c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c9MouseClicked(evt);
            }
        });

        c20.setText("20");
        c20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c20MouseClicked(evt);
            }
        });

        c19.setText("19");
        c19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c19MouseClicked(evt);
            }
        });

        c17.setText("17");
        c17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c17MouseClicked(evt);
            }
        });

        c16.setText("16");
        c16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c16MouseClicked(evt);
            }
        });

        c18.setText("18");
        c18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c18MouseClicked(evt);
            }
        });

        c15.setText("15");
        c15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1)
                            .addComponent(c2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c13))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(c15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c20)
                        .addGap(13, 13, 13)))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c7)
                            .addComponent(c9)
                            .addComponent(c11)
                            .addComponent(c13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c8)
                            .addComponent(c10)
                            .addComponent(c12)
                            .addComponent(c14)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c3)
                            .addComponent(c5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c4)
                            .addComponent(c6)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c20)
                    .addComponent(c19)
                    .addComponent(c15)
                    .addComponent(c17)
                    .addComponent(c16)
                    .addComponent(c18))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void array(){
        try{
            dbconnect db=new dbconnect();
            db.connect();
            String sql="select * from seats where bid=?";
            db.pst= db.con.prepareStatement(sql);
            db.pst.setInt(1,Login.bid);
            db.rs=db.pst.executeQuery();
            
            
            if(db.rs.next()){
            for(int i=3;i<=22;i++){
             list.add(db.rs.getInt(i));
               }
            }
            
            /*for(int i=0;i<list.size();i++){
            System.out.println(list.get(i).toString());
            }*/
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void check(){
                if(list.get(0).equals(1))
                c1.setEnabled(false);
                
                if(list.get(1).equals(1))
                c2.setEnabled(false);
                
                if(list.get(2).equals(1))
                c3.setEnabled(false);
                
                if(list.get(3).equals(1))
                c4.setEnabled(false);
                
                if(list.get(4).equals(1))
                c5.setEnabled(false);
                
                if(list.get(5).equals(1))
                c6.setEnabled(false);
                
                if(list.get(6).equals(1))
                c7.setEnabled(false);
                
                if(list.get(7).equals(1))
                c8.setEnabled(false);
                if(list.get(8).equals(1))
                c9.setEnabled(false);
                if(list.get(9).equals(1))
                c10.setEnabled(false);
                if(list.get(10).equals(1))
                c11.setEnabled(false);
                if(list.get(11).equals(1))
                c12.setEnabled(false);
                if(list.get(12).equals(1))
                c13.setEnabled(false);
                if(list.get(13).equals(1))
                c14.setEnabled(false);
                if(list.get(14).equals(1))
                c15.setEnabled(false);
                if(list.get(15).equals(1))
                c16.setEnabled(false);
                if(list.get(16).equals(1))
                c17.setEnabled(false);
                if(list.get(17).equals(1))
                c18.setEnabled(false);
                if(list.get(18).equals(1))
                c19.setEnabled(false);
                if(list.get(19).equals(1))
                c20.setEnabled(false);
                
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            dbconnect db=new dbconnect();
            db.connect();
            
            String sql="update seats set s1="+list.get(0)+",s2="+list.get(1)+",s3="+list.get(2)+",s4="+list.get(3)+",s5="+list.get(4)+",s6="+list.get(5)+",s7="+list.get(6)+",s8="+list.get(7)+",s9="+list.get(8)+",s10="+list.get(9)+",s11="+list.get(10)+",s12="+list.get(11)+",s13="+list.get(12)+",s14="+list.get(13)+",s15="+list.get(14)+",s16="+list.get(15)+",s17="+list.get(16)+",s18="+list.get(17)+",s19="+list.get(18)+",s20="+list.get(19)+" where bid="+Login.bid+"";   
            db.pst= db.con.prepareStatement(sql);
            
             if(db.pst.executeUpdate() != 0){
                            bodr bd = new bodr();
                            bd.setVisible(true);
                            this.setVisible(false);
                            }else{
                            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                            }
                            }
                            catch(Exception e){
                            JOptionPane.showMessageDialog(null,e);
                            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
       
        if(c1.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(0,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(0,0);
        }
   
    }//GEN-LAST:event_c1ActionPerformed

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
        // TODO add your handling code here:
        if(c2.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(1,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(1,0);
        }
    }//GEN-LAST:event_c2MouseClicked

    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked
        // TODO add your handling code here:
        if(c3.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(2,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(2,0);
        }
    }//GEN-LAST:event_c3MouseClicked

    private void c4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MouseClicked
        // TODO add your handling code here:
        if(c4.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(3,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(3,0);
        }
    }//GEN-LAST:event_c4MouseClicked

    private void c5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MouseClicked
        // TODO add your handling code here:
        if(c5.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(4,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(4,0);
        }
    }//GEN-LAST:event_c5MouseClicked

    private void c6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6MouseClicked
        // TODO add your handling code here:
        if(c6.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(5,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(5,0);
        }
    }//GEN-LAST:event_c6MouseClicked

    private void c7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c7MouseClicked
        // TODO add your handling code here:
        if(c7.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(6,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(6,0);
        }
    }//GEN-LAST:event_c7MouseClicked

    private void c8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c8MouseClicked
        // TODO add your handling code here:
        if(c8.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(7,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(7,0);
        }
    }//GEN-LAST:event_c8MouseClicked

    private void c9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c9MouseClicked
        // TODO add your handling code here:
        if(c9.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(8,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(8,0);
        }
    }//GEN-LAST:event_c9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new bodr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void c10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c10MouseClicked
        // TODO add your handling code here:
        if(c10.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(9,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(9,0);
        }
    }//GEN-LAST:event_c10MouseClicked

    private void c12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c12MouseClicked
        // TODO add your handling code here:
        if(c12.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(11,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(11,0);
        }
    }//GEN-LAST:event_c12MouseClicked

    private void c14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c14MouseClicked
        // TODO add your handling code here:
        if(c14.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(13,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(13,0);
        }
    }//GEN-LAST:event_c14MouseClicked

    private void c15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c15MouseClicked
        // TODO add your handling code here:
        if(c15.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(14,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(14,0);
        }
    }//GEN-LAST:event_c15MouseClicked

    private void c13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c13MouseClicked
        // TODO add your handling code here:
        if(c13.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(12,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(12,0);
        }
    }//GEN-LAST:event_c13MouseClicked

    private void c11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c11MouseClicked
        // TODO add your handling code here:
        if(c11.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(10,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(10,0);
        }
    }//GEN-LAST:event_c11MouseClicked

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void c17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c17MouseClicked
        // TODO add your handling code here:
        if(c17.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(16,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(16,0);
        }
    }//GEN-LAST:event_c17MouseClicked

    private void c16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c16MouseClicked
        // TODO add your handling code here:
        if(c16.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(15,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(15,0);
        }
    }//GEN-LAST:event_c16MouseClicked

    private void c18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c18MouseClicked
        // TODO add your handling code here:
        if(c18.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(17,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(17,0);
        }
    }//GEN-LAST:event_c18MouseClicked

    private void c20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c20MouseClicked
        // TODO add your handling code here:
        if(c20.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(19,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(19,0);
        }
    }//GEN-LAST:event_c20MouseClicked

    private void c19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c19MouseClicked
        // TODO add your handling code here:
        if(c19.isSelected()){
        Login.price+=Login.bprice;
        Login.seat+=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(18,1);
        }
        else{
        Login.price-=Login.bprice;
        Login.seat-=1;
        lbprice.setText("₹ "+Integer.toString(Login.price));
        lbseats.setText("Seats "+Integer.toString(Login.seat));
        list.set(18,0);
        }
    }//GEN-LAST:event_c19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c15;
    private javax.swing.JCheckBox c16;
    private javax.swing.JCheckBox c17;
    private javax.swing.JCheckBox c18;
    private javax.swing.JCheckBox c19;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c20;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbprice;
    public javax.swing.JLabel lbseats;
    public javax.swing.JLabel lsbname;
    // End of variables declaration//GEN-END:variables
}
